"""
Care Priority Dashboard
Context-Aware Care Gap Detection & Community Vulnerability System
Island Health, BC — Hackathon Demo

Run: streamlit run app.py
"""

import sys, os
sys.path.insert(0, os.path.dirname(__file__))

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

from data_pipeline import load_all
from patient_scorer import score_patients, categorize_flags, compute_system_impact
from community_scorer import score_communities
from priority_engine import (compute_priorities, summary_stats,
                             cohort_outcomes, simulate_intervention,
                             simulate_community_scenario)
from llm_explainer import generate_explanation

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Care Prioritization · Island Health",
    page_icon="🏥",
    layout="wide",
)

TIER_COLORS = {
    "CRITICAL": "#d62728",
    "HIGH":     "#ff7f0e",
    "MEDIUM":   "#f5c518",
    "LOW":      "#2ca02c",
}
TIER_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW"]

# ── Data loading (cached) ─────────────────────────────────────────────────────
@st.cache_data(show_spinner="Loading and scoring patient data…")
def build_data():
    data               = load_all()
    scored             = score_patients(data["master"])
    comm_sc            = score_communities(data["community"])
    priorities, tholds = compute_priorities(scored, comm_sc)
    stats              = summary_stats(priorities)
    outcomes           = cohort_outcomes(priorities)
    return (priorities, comm_sc, stats, tholds, outcomes,
            data["opioid_trend"], data["wait_times"], data["bc_wait"])

(priorities, comm_scores, stats, thresholds, outcomes,
 opioid_trend, wait_times, bc_wait) = build_data()

# ── Header ────────────────────────────────────────────────────────────────────
st.title("🏥 AI-Enabled Care Prioritization System")
st.caption(
    "Context-aware care gap detection for Island Health, BC · "
    "Combines patient clinical risk (Track 1) with community vulnerability (Track 2)"
)

# ── Methodology note ──────────────────────────────────────────────────────────
with st.expander("📐 **About this model — methodology, linkage, and limitations**"):
    st.markdown("""
### What this tool does

This dashboard is a **prioritization framework for care coordination outreach** —
it ranks patients by how urgently they may benefit from proactive follow-up.
It is **not** a diagnostic tool, a causal model, or a validated clinical risk predictor.

### How the two scores are computed

| Score | Source | Level | Method |
|-------|--------|-------|--------|
| **Patient risk** (0–100) | Track 1: encounters, labs, medications | Individual | Rule-based: ED frequency, chronic disease control, polypharmacy, AMA history, follow-up gap, wait burden, language barrier |
| **Community vulnerability** (0–100) | Track 2: BC community health indicators | Area (CHSA) | Weighted composite of 6 normalized indicators (% without family doctor, poverty rate, opioid overdose rate, chronic disease burden, mental health hospitalization, ER visit rate) |

The two scores are **computed independently**, then combined as:

> `combined_score = 0.60 × patient_risk + 0.40 × community_vulnerability`

The weights are explicit and adjustable in `config.py`.

### How patients are linked to communities

Patient postal codes (Forward Sortation Area / first 3 characters) are mapped to
BC Community Health Service Areas (CHSAs) via geographic approximation.
This follows the **area-based linkage** approach commonly used in Canadian health
inequality analysis (CIHI equity stratification via PCCF/PCCF+).

### What the community score does and does not mean

- ✅ **Does mean:** This patient lives in a community where structural barriers to
  primary care access are more prevalent.
- ❌ **Does not mean:** This specific patient has no family doctor, or that their
  community environment *caused* their clinical risk.

The community score is a **contextual modifier**, not an individual-level fact.

### Key limitations

1. **Ecological fallacy:** Area-level statistics are used as individual-level context.
2. **No causal validation:** Community-level access barriers are not proven to cause repeat ED use in this dataset.
3. **Synthetic data:** All Track 1 patient data is generated by Synthea.
4. **FSA → CHSA mapping is approximate:** Based on known BC postal code geography.
5. **Intervention estimates are modelled, not observed:** The 30% ED visit reduction is an assumption.
6. **Scenario projections are sensitivity analyses**, not predictions — they show how the scoring framework responds to input changes.

### Intended use

Designed for **care coordinators and planning teams** to support outreach prioritization
and community-level resource planning. Use alongside clinical judgement.
""")

# ── Cohort Outcomes ───────────────────────────────────────────────────────────
st.subheader("Cohort Outcomes — High-Priority Patients")
o1, o2, o3, o4 = st.columns(4)
o1.metric("🔴🟠 HP without Family Doctor", outcomes["hp_no_family_doctor"],
          help=f"CRITICAL+HIGH in communities ≥20% without GP (of {outcomes['high_priority_count']})")
o2.metric("🔁 Repeat ED Visitors (≥3/yr)", outcomes["hp_repeat_ed"])
o3.metric("💉 Diabetics Overdue", outcomes["hp_diabetics_overdue"])
o4.metric("🛡️ Est. Preventable ED/yr", f"{outcomes['preventable_ed_visits']:,}",
          delta=f"~${outcomes['preventable_cost_cad']:,.0f} potential savings",
          delta_color="inverse")

st.divider()

# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.header("Filters")
    selected_tiers = st.multiselect(
        "Priority tier", options=TIER_ORDER, default=["CRITICAL", "HIGH"])
    selected_communities = st.multiselect(
        "Community",
        options=sorted(priorities["chsa_name"].dropna().unique()),
        default=[], placeholder="All communities")
    min_risk = st.slider("Minimum patient risk score", 0, 100, 0)

    st.divider()
    st.caption("**Score weights:** Patient risk 60% · Community vuln. 40%")

    st.divider()
    st.subheader("🎯 Intervention Planner")
    st.caption("*If your team can outreach N patients this week…*")
    n_outreach = st.slider("Outreach capacity", 10, 200, 50, 10)

# ── Apply filters ─────────────────────────────────────────────────────────────
filtered = priorities.copy()
if selected_tiers:
    filtered = filtered[filtered["priority_tier"].isin(selected_tiers)]
if selected_communities:
    filtered = filtered[filtered["chsa_name"].isin(selected_communities)]
filtered = filtered[filtered["risk_score"] >= min_risk]


# ══════════════════════════════════════════════════════════════════════════════
#                          THREE TABS
# ══════════════════════════════════════════════════════════════════════════════
tab1, tab2, tab3 = st.tabs([
    "👤 Priority Queue",
    "🏘️ Community Insights",
    "🔬 Scenario Simulator",
])


# ══════════════════════════════════════════════════════════════════════════════
# TAB 1 — Priority Queue
# ══════════════════════════════════════════════════════════════════════════════
with tab1:
    col_left, col_right = st.columns([3, 2])

    with col_right:
        # Tier donut
        tier_counts = filtered["priority_tier"].value_counts().reindex(TIER_ORDER, fill_value=0)
        fig_donut = go.Figure(go.Pie(
            labels=tier_counts.index, values=tier_counts.values,
            hole=0.55,
            marker_colors=[TIER_COLORS[t] for t in tier_counts.index],
            textinfo="label+value",
        ))
        fig_donut.update_layout(title="Priority Tier Breakdown",
                                showlegend=False, height=260,
                                margin=dict(l=0, r=0, t=40, b=0))
        st.plotly_chart(fig_donut, use_container_width=True)

        # Top risk flags
        st.markdown("**Most Common Risk Flags**")
        all_flags = [f for flags in filtered["risk_flags"] for f in flags]
        if all_flags:
            flag_series = pd.Series(all_flags).value_counts().head(6)
            fig_flags = px.bar(
                x=flag_series.values, y=flag_series.index, orientation="h",
                labels={"x": "Patients", "y": ""},
                color=flag_series.values, color_continuous_scale="Oranges",
                height=240,
            )
            fig_flags.update_layout(margin=dict(l=0, r=0, t=0, b=0),
                                     coloraxis_showscale=False)
            st.plotly_chart(fig_flags, use_container_width=True)

        # Intervention planner results
        st.markdown("---")
        st.markdown(f"**🎯 Outreach top {n_outreach} patients**")
        sim = simulate_intervention(priorities, n_outreach)
        s1, s2 = st.columns(2)
        s1.metric("Avoided ED visits/yr", sim["avoided_ed_visits"])
        s2.metric("Cost savings/yr", f"${sim['avoided_cost_cad']:,.0f}")
        if sim["key_conditions"]:
            for cond in sim["key_conditions"]:
                st.caption(f"• {cond}")

    with col_left:
        st.subheader(f"Priority Queue  ({len(filtered):,} patients)")
        if filtered.empty:
            st.info("No patients match the current filters.")
        else:
            page_size = 20
            total_pages = max(1, (len(filtered) - 1) // page_size + 1)
            page = st.number_input("Page", 1, total_pages, 1, 1)
            page_df = filtered.iloc[(page - 1) * page_size : page * page_size]

            for _, row in page_df.iterrows():
                tier  = row["priority_tier"]
                emoji = row["priority_emoji"]

                with st.expander(
                    f"{emoji} **{tier}** · {row['patient_id']} · "
                    f"Age {int(row['age'])} {row['sex']} · "
                    f"{row['chsa_name']} · Score {row['combined_score']:.0f}/100"
                ):
                    c_a, c_b, c_c = st.columns(3)
                    c_a.metric("Patient Risk",    f"{row['risk_score']:.0f}/100")
                    c_b.metric("Community Vuln.", f"{row['vulnerability_score']:.0f}/100")
                    c_c.metric("Combined Score",  f"{row['combined_score']:.0f}/100")

                    # "Why now?" structured reasoning
                    flags   = row.get("risk_flags", [])
                    cats    = categorize_flags(flags)
                    impacts = compute_system_impact(row)

                    why1, why2, why3 = st.columns(3)
                    with why1:
                        st.markdown("**⚕️ Clinical Need**")
                        for f in (cats["clinical_need"] or ["_No acute clinical flags_"]):
                            st.markdown(f"- {f}")
                    with why2:
                        st.markdown("**🚧 Access Barrier**")
                        barriers = cats["access_barrier"].copy()
                        gp_pct = row.get("pct_without_family_doctor", 0)
                        if gp_pct >= 15 and not any("GP" in b or "family" in b.lower() for b in barriers):
                            barriers.insert(0, f"{gp_pct:.0f}% in community lack a family doctor")
                        for f in (barriers or ["_No significant access barriers_"]):
                            st.markdown(f"- {f}")
                    with why3:
                        st.markdown("**📊 System Impact**")
                        for imp in impacts:
                            st.markdown(f"- {imp}")

                    st.info(f"**Recommended action:** {row['priority_action']}")

                    if st.button("💬 Generate AI rationale", key=f"btn_{row['patient_id']}"):
                        with st.spinner("Generating explanation…"):
                            explanation = generate_explanation(row.to_dict())
                        st.success(explanation)


# ══════════════════════════════════════════════════════════════════════════════
# TAB 2 — Community Insights
# ══════════════════════════════════════════════════════════════════════════════
with tab2:
    ci_left, ci_right = st.columns([1, 1])

    with ci_left:
        st.subheader("Community Vulnerability Ranking (all 78 BC communities)")
        # Full BC bar chart
        comm_sorted = comm_scores.sort_values("vulnerability_score", ascending=True)
        # Mark patient-linked communities
        patient_chsas = set(priorities["chsa_code"].unique())
        comm_sorted["has_patients"] = comm_sorted["chsa_code"].isin(patient_chsas)
        comm_sorted["label"] = comm_sorted.apply(
            lambda r: f"★ {r['chsa_name']}" if r["has_patients"] else r["chsa_name"], axis=1
        )
        fig_all = px.bar(
            comm_sorted,
            x="vulnerability_score", y="label", orientation="h",
            color="vulnerability_score", color_continuous_scale="Reds",
            labels={"vulnerability_score": "Vulnerability Score", "label": ""},
            height=max(400, len(comm_sorted) * 18),
        )
        fig_all.update_layout(margin=dict(l=0, r=0, t=0, b=0),
                               coloraxis_showscale=False, yaxis_dtick=1)
        st.plotly_chart(fig_all, use_container_width=True)
        st.caption("★ = communities with patients in the Track 1 dataset")

    with ci_right:
        st.subheader("Risk vs Vulnerability")
        comm_summary = (
            priorities.groupby("chsa_name")
            .agg(
                avg_risk=("risk_score", "mean"),
                avg_vuln=("vulnerability_score", "mean"),
                patient_count=("patient_id", "count"),
                critical_count=("priority_tier", lambda x: (x == "CRITICAL").sum()),
            )
            .reset_index()
        )
        fig_scatter = px.scatter(
            comm_summary, x="avg_vuln", y="avg_risk",
            size="patient_count", color="critical_count",
            color_continuous_scale="Reds", text="chsa_name",
            labels={"avg_vuln": "Community Vulnerability",
                    "avg_risk": "Avg Patient Risk",
                    "critical_count": "Critical Pts"},
            height=350,
        )
        fig_scatter.update_traces(textposition="top center")
        fig_scatter.update_layout(margin=dict(l=0, r=0, t=10, b=0))
        st.plotly_chart(fig_scatter, use_container_width=True)

        # BC Provincial Context
        st.markdown("---")
        st.subheader("🏔️ BC Provincial Context")

        st.markdown("**Opioid Crisis Trend** — deaths per 100k")
        fig_opioid = px.area(
            opioid_trend, x="year", y="rate_per_100k", markers=True,
            labels={"rate_per_100k": "Deaths / 100k", "year": ""},
            color_discrete_sequence=["#d62728"], height=240,
        )
        fig_opioid.add_vline(x=2020, line_dash="dash", line_color="gray",
                             annotation_text="COVID-19", annotation_position="top right")
        fig_opioid.update_layout(margin=dict(l=0, r=0, t=10, b=0))
        st.plotly_chart(fig_opioid, use_container_width=True)

        st.markdown("**Elective Procedure Wait Times (BC)**")
        bc_recent = (
            wait_times[(wait_times["province"] == "BC") &
                       (wait_times["year"] >= wait_times["year"].max() - 2)]
            .groupby("procedure")["median_wait_days"].mean().round(1)
            .reset_index().sort_values("median_wait_days", ascending=True)
        )
        bc_recent["flag"] = bc_recent["median_wait_days"].apply(
            lambda d: "Long wait" if d >= 60 else "Within range"
        )
        fig_wait = px.bar(
            bc_recent, x="median_wait_days", y="procedure", orientation="h",
            color="flag",
            color_discrete_map={"Long wait": "#ff7f0e", "Within range": "#2ca02c"},
            labels={"median_wait_days": "Median days", "procedure": ""},
            height=260,
        )
        fig_wait.update_layout(margin=dict(l=0, r=0, t=10, b=0),
                               legend=dict(title="", orientation="h", y=1.08))
        st.plotly_chart(fig_wait, use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# TAB 3 — Scenario Simulator
# ══════════════════════════════════════════════════════════════════════════════
with tab3:
    st.subheader("🔬 Community Scenario Simulator")
    st.markdown(
        "**What if** primary care attachment improves in a specific community? "
        "This tool re-calculates vulnerability and patient priority scores to estimate impact."
    )

    # Community selector — only communities with patients
    patient_communities = (
        comm_scores[comm_scores["chsa_code"].isin(priorities["chsa_code"].unique())]
        .sort_values("vulnerability_score", ascending=False)
    )
    community_options = {
        f"{r['chsa_name']}  (vuln: {r['vulnerability_score']:.0f}, "
        f"unattached: {r['pct_without_family_doctor']:.1f}%)": r["chsa_code"]
        for _, r in patient_communities.iterrows()
    }

    sc1, sc2 = st.columns([2, 1])
    with sc1:
        selected_label = st.selectbox("Select community", options=list(community_options.keys()))
    selected_chsa = community_options[selected_label]

    with sc2:
        max_unattached = float(
            comm_scores.loc[comm_scores["chsa_code"] == selected_chsa,
                            "pct_without_family_doctor"].iloc[0]
        )
        improvement = st.slider(
            "Improve primary care attachment by (pp)",
            min_value=0.0, max_value=min(max_unattached, 25.0),
            value=min(5.0, max_unattached), step=1.0,
            help="Percentage points reduction in '% without family doctor'"
        )

    # Run scenario
    scenario = simulate_community_scenario(priorities, comm_scores, selected_chsa, improvement)

    # ── Results ───────────────────────────────────────────────────────────────
    st.markdown("---")
    r1, r2, r3 = st.columns(3)

    with r1:
        st.markdown("### Current State")
        st.metric("Unattached rate", f"{scenario['current_unattached']}%")
        st.metric("Vulnerability score", f"{scenario['current_vuln']}/100")
        st.metric("Patients in community", scenario["n_patients"])
        # Before tier breakdown
        st.markdown("**Priority tier breakdown**")
        for t in TIER_ORDER:
            count = scenario["before_tiers"].get(t, 0)
            if count:
                st.markdown(f"- {t}: **{count}**")

    with r2:
        st.markdown("### After Scenario")
        st.metric("Unattached rate",
                  f"{scenario['new_unattached']}%",
                  delta=f"-{improvement:.0f}pp",
                  delta_color="inverse")
        st.metric("Vulnerability score",
                  f"{scenario['new_vuln']:.1f}/100",
                  delta=f"{scenario['new_vuln'] - scenario['current_vuln']:.1f}",
                  delta_color="inverse")
        st.metric("Patients in community", scenario["n_patients"])
        st.markdown("**Priority tier breakdown**")
        for t in TIER_ORDER:
            before = scenario["before_tiers"].get(t, 0)
            after  = scenario["after_tiers"].get(t, 0)
            diff   = after - before
            if before or after:
                arrow = f" ({diff:+d})" if diff != 0 else ""
                st.markdown(f"- {t}: **{after}**{arrow}")

    with r3:
        st.markdown("### Projected Impact")
        st.metric("Patients improved tier", scenario["n_improved"],
                  help="Number of patients who dropped to a lower-urgency tier")
        st.metric("Fewer high-priority patients", scenario["avoided_hp"],
                  help="Patients who moved out of CRITICAL/HIGH")
        st.metric("Est. avoided ED visits/yr", scenario["avoided_ed_visits"])
        st.metric("Est. cost savings/yr", f"${scenario['avoided_cost']:,.0f} CAD")

    # ── Before/After comparison chart ─────────────────────────────────────────
    st.markdown("---")
    chart_data = []
    for t in TIER_ORDER:
        chart_data.append({"Tier": t, "State": "Before", "Patients": scenario["before_tiers"].get(t, 0)})
        chart_data.append({"Tier": t, "State": "After",  "Patients": scenario["after_tiers"].get(t, 0)})
    chart_df = pd.DataFrame(chart_data)

    fig_compare = px.bar(
        chart_df, x="Tier", y="Patients", color="State",
        barmode="group",
        color_discrete_map={"Before": "#ef5350", "After": "#66bb6a"},
        title=f"Priority Tier Shift — {scenario['community_name']}",
        height=320,
    )
    fig_compare.update_layout(margin=dict(l=0, r=0, t=40, b=0))
    st.plotly_chart(fig_compare, use_container_width=True)

    # Narrative
    st.info(
        f"**Planning estimate:** Reducing the unattached rate in **{scenario['community_name']}** "
        f"from {scenario['current_unattached']}% to {scenario['new_unattached']}% would lower "
        f"the community vulnerability score from {scenario['current_vuln']} to {scenario['new_vuln']:.1f}, "
        f"moving **{scenario['n_improved']}** patient(s) to lower-urgency tiers and potentially "
        f"avoiding **{scenario['avoided_ed_visits']}** ED visits/year "
        f"(~${scenario['avoided_cost']:,.0f} CAD)."
    )
    st.caption(
        "⚠️ This is a sensitivity analysis within the scoring framework, not a causal prediction. "
        "Community-level improvements affect the contextual modifier only; "
        "individual patient clinical risk scores remain unchanged."
    )


# ── Footer ────────────────────────────────────────────────────────────────────
st.divider()
st.caption(
    "**Data**: Synthea synthetic patients (Track 1) + BC Community Health Profiles, "
    "CIHI Wait Times, Opioid Surveillance (Track 2) · "
    "**Linkage**: FSA-to-CHSA geographic approximation (Island Health catchment) · "
    "**Scoring**: Rule-based patient risk + area-based community vulnerability, combined with explicit weights · "
    "**AI**: Claude 3.5 Haiku for natural-language rationale generation · "
    "Prioritization framework for outreach support — not a diagnostic or causal prediction tool."
)
